export type ThemeColors = {
  TEXT_PRIMARY: string;
  TEXT_SECONDARY: string;
  TEXT_GRADIENT_START: string;
  TEXT_GRADIENT_END: string;
  TEXT_GRAY: string;
  BACKGROUND: string;
  TEXT_DARK: string;
  TEXT_LIGHT: string;
  TEXT_SHADE: string;
  TEXT_DARK_2: string;
  BUTTON_FILLED_TEXT_COLOR: string;
  BUTTON_FILLED_TEXT_COLOR_DISABLED: string;
  BUTTON_FILLED_BORDER_COLOR: string;
  BUTTON_FILLED_BORDER_COLOR_DISABLED: string;
  BUTTON_FILLED_BACKGROUND_COLOR: string;
  BUTTON_FILLED_BACKGROUND_COLOR_DISABLED: string;
  BUTTON_OUTLINE_TEXT_COLOR: string;
  BUTTON_OUTLINE_TEXT_COLOR_DISABLED: string;
  BUTTON_OUTLINE_BORDER_COLOR: string;
  BUTTON_OUTLINE_BORDER_COLOR_DISABLED: string;
  BUTTON_DESTRUCTIVE_TEXT_COLOR: string;
  BUTTON_DESTRUCTIVE_TEXT_COLOR_DISABLED: string;
  BUTTON_DESTRUCTIVE_BACKGROUND_COLOR: string;
  BUTTON_DESTRUCTIVE_BACKGROUND_COLOR_DISABLED: string;
};

export enum Theme {
  DARK = "dark",
  LIGHT = "light",
  SYSTEM = "system",
}

export const DarkTheme: ThemeColors = {
  TEXT_PRIMARY: "#039EF2",
  TEXT_SECONDARY: "#FFFFFF",
  TEXT_GRADIENT_START: "#039EF2",
  TEXT_GRADIENT_END: "#027EC2",
  TEXT_GRAY: "#667085",
  BACKGROUND: "#00070B",
  TEXT_DARK: "#000000",
  TEXT_LIGHT: "#FFFFFF",
  TEXT_SHADE: "#FCFCFD",
  TEXT_DARK_2: "#FFFFFF",
  BUTTON_FILLED_TEXT_COLOR: "#FFFFFF",
  BUTTON_FILLED_TEXT_COLOR_DISABLED: "#FFFFFF",
  BUTTON_FILLED_BACKGROUND_COLOR:
    "linear-gradient(180deg, #039EF2 0%, #027EC2 100%)",
  BUTTON_FILLED_BACKGROUND_COLOR_DISABLED: "#E6F5FE",
  BUTTON_FILLED_BORDER_COLOR:
    "linear-gradient(180deg, #039EF2 0%, #027EC2 100%)",
  BUTTON_FILLED_BORDER_COLOR_DISABLED: "#E6F5FE",
  BUTTON_OUTLINE_TEXT_COLOR: "#FFFFFF",
  BUTTON_OUTLINE_TEXT_COLOR_DISABLED: "#D0D5DD",
  BUTTON_OUTLINE_BORDER_COLOR: "#D0D5DD",
  BUTTON_OUTLINE_BORDER_COLOR_DISABLED: "#EAECF0",
  BUTTON_DESTRUCTIVE_TEXT_COLOR: "#F04438",
  BUTTON_DESTRUCTIVE_TEXT_COLOR_DISABLED: "#F04438",
  BUTTON_DESTRUCTIVE_BACKGROUND_COLOR: "#FEF3F2",
  BUTTON_DESTRUCTIVE_BACKGROUND_COLOR_DISABLED: "#FEF3F2",
};

export const LightTheme: ThemeColors = {
  TEXT_PRIMARY: "#039EF2",
  TEXT_SECONDARY: "#FFFFFF",
  TEXT_GRADIENT_START: "#039EF2",
  TEXT_GRADIENT_END: "#027EC2",
  TEXT_GRAY: "#667085",
  BACKGROUND: "#FFFFFF",
  TEXT_DARK: "#000000",
  TEXT_LIGHT: "#FFFFFF",
  TEXT_SHADE: "#757575",
  TEXT_DARK_2: "#101928",
  BUTTON_FILLED_TEXT_COLOR: "#FFFFFF",
  BUTTON_FILLED_TEXT_COLOR_DISABLED: "#FFFFFF",
  BUTTON_FILLED_BACKGROUND_COLOR:
    "linear-gradient(180deg, #039EF2 0%, #027EC2 100%)",
  BUTTON_FILLED_BACKGROUND_COLOR_DISABLED: "#E6F5FE",
  BUTTON_FILLED_BORDER_COLOR:
    "linear-gradient(180deg, #039EF2 0%, #027EC2 100%)",
  BUTTON_FILLED_BORDER_COLOR_DISABLED: "#E6F5FE",
  BUTTON_OUTLINE_TEXT_COLOR: "#00070B",
  BUTTON_OUTLINE_TEXT_COLOR_DISABLED: "#D0D5DD",
  BUTTON_OUTLINE_BORDER_COLOR: "#D0D5DD",
  BUTTON_OUTLINE_BORDER_COLOR_DISABLED: "#EAECF0",
  BUTTON_DESTRUCTIVE_TEXT_COLOR: "#F04438",
  BUTTON_DESTRUCTIVE_TEXT_COLOR_DISABLED: "#F04438",
  BUTTON_DESTRUCTIVE_BACKGROUND_COLOR: "#FEF3F2",
  BUTTON_DESTRUCTIVE_BACKGROUND_COLOR_DISABLED: "#FEF3F2",
};
